version: '3.8'

services:
  repertoiresearchengine:
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  repertoiremanagementservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5010:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  usermanagementservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5020:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro