version: '3.8'

services:
  repertoiresearchengine:
    image: ${DOCKER_REGISTRY-}repertoiresearchengine
    build:
      context: ../../
      dockerfile: src/RepertoireSearchEngine/RepertoireSearchEngine.Server/Dockerfile

  repertoiremanagementservice:
    image: ${DOCKER_REGISTRY-}repertoiremanagementservice
    build:
      context: ../../
      dockerfile: src/RepertoireManagementService/RepertoireManagementService.Api/Dockerfile

  usermanagementservice:
    image: ${DOCKER_REGISTRY-}usermanagementservice
    build:
      context: ../../
      dockerfile: src/UserManagementService/UserManagementService.Api/Dockerfile