version: '3.8'

services:
  repertoiresearchengine:
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5010:80"

  repertoiremanagementservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5020:80"
  
  usermanagementservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5030:80"